# Generated by Django 3.2.3 on 2021-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210528_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rent',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
    ]
