# Generated by Django 3.2.3 on 2021-06-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_car_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
