# Generated by Django 3.2.3 on 2021-06-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_car_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='modelNo',
        ),
    ]
