# Generated by Django 3.2.3 on 2021-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_car_modelno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
