# Generated by Django 3.2.3 on 2021-06-03 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_car_mileage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarRent',
            new_name='RentCar',
        ),
    ]
